package com.ecommerce.checkout.dto.response;

import com.ecommerce.checkout.enums.OrderStatus;
import com.ecommerce.checkout.enums.PaymentStatus;
import java.math.BigDecimal;
import java.util.List;

public class CheckoutResponse {
    private Long orderId; private Long userId; private BigDecimal totalAmount; private BigDecimal discountAmount; private BigDecimal finalAmount; private PaymentStatus paymentStatus; private OrderStatus orderStatus; private List<CartItemResponse> items;
    public CheckoutResponse() {}
    public CheckoutResponse(Long orderId, Long userId, BigDecimal totalAmount, BigDecimal discountAmount, BigDecimal finalAmount, PaymentStatus paymentStatus, OrderStatus orderStatus, List<CartItemResponse> items){this.orderId=orderId;this.userId=userId;this.totalAmount=totalAmount;this.discountAmount=discountAmount;this.finalAmount=finalAmount;this.paymentStatus=paymentStatus;this.orderStatus=orderStatus;this.items=items;}
    public Long getOrderId(){return orderId;} public void setOrderId(Long orderId){this.orderId=orderId;} public Long getUserId(){return userId;} public void setUserId(Long userId){this.userId=userId;} public BigDecimal getTotalAmount(){return totalAmount;} public void setTotalAmount(BigDecimal totalAmount){this.totalAmount=totalAmount;} public BigDecimal getDiscountAmount(){return discountAmount;} public void setDiscountAmount(BigDecimal discountAmount){this.discountAmount=discountAmount;} public BigDecimal getFinalAmount(){return finalAmount;} public void setFinalAmount(BigDecimal finalAmount){this.finalAmount=finalAmount;} public PaymentStatus getPaymentStatus(){return paymentStatus;} public void setPaymentStatus(PaymentStatus paymentStatus){this.paymentStatus=paymentStatus;} public OrderStatus getOrderStatus(){return orderStatus;} public void setOrderStatus(OrderStatus orderStatus){this.orderStatus=orderStatus;} public List<CartItemResponse> getItems(){return items;} public void setItems(List<CartItemResponse> items){this.items=items;}
    public static Builder builder(){return new Builder();}
    public static class Builder{private Long orderId;private Long userId;private BigDecimal totalAmount;private BigDecimal discountAmount;private BigDecimal finalAmount;private PaymentStatus paymentStatus;private OrderStatus orderStatus;private List<CartItemResponse> items; public Builder orderId(Long orderId){this.orderId=orderId;return this;} public Builder userId(Long userId){this.userId=userId;return this;} public Builder totalAmount(BigDecimal totalAmount){this.totalAmount=totalAmount;return this;} public Builder discountAmount(BigDecimal discountAmount){this.discountAmount=discountAmount;return this;} public Builder finalAmount(BigDecimal finalAmount){this.finalAmount=finalAmount;return this;} public Builder paymentStatus(PaymentStatus paymentStatus){this.paymentStatus=paymentStatus;return this;} public Builder orderStatus(OrderStatus orderStatus){this.orderStatus=orderStatus;return this;} public Builder items(List<CartItemResponse> items){this.items=items;return this;} public CheckoutResponse build(){return new CheckoutResponse(orderId,userId,totalAmount,discountAmount,finalAmount,paymentStatus,orderStatus,items);} }
}
